---
cloud:
  aws:
    credentials:
      access-key: <access-key>
      secret-key: <secret-key>
    end-point:
      uri: <uri>
    region:
      auto: false
      static: ap-south-1
    stack:
      auto: false
server:
  port: 9001
